import { LICENSE_URL, SIGN_IN_URL, SIGN_UP_URL, SOURCE_URL } from '@/lib/config';
import { channelsEn } from './channels.en';
import { featuresEn } from './features.en';
import type { Dict } from './types';

// English copy. Sentence case, no emoji, no invented stats or customers. Claims about the
// product follow the app's code: calendar views are day, week, month and the board; there
// are no best-time recommendations and no approval step; the agent can't delete posts.
export const en: Dict = {
  lang: 'en',
  dir: 'ltr',
  base: '',
  numberLocale: 'en-US',
  meta: {
    title: 'Tadween — LinkedIn scheduling, written in two languages',
    description:
      'Plan LinkedIn posts for your profile and pages, preview them as LinkedIn will show them and publish on time. In English and Arabic, with 30+ channels.',
    pricingTitle: 'Pricing — Tadween',
    pricingDescription:
      'Four plans for people, brands and agencies on LinkedIn. Every plan starts with seven days free. Prices in Egyptian pounds or US dollars.',
    ogLocale: 'en_US',
    features: {
      title: 'Features: calendar, board, composer and AI agent | Tadween',
      description:
        'Every tool in Tadween: calendar and board, a composer with network previews and Arabic writing, media library, analytics, team tools and an AI agent.',
    },
    agent: {
      title: 'AI agent for social media scheduling | Tadween',
      description:
        'Ask Tadween’s agent to write and schedule LinkedIn posts in English or Arabic, or connect Claude, ChatGPT and Cursor to your calendar.',
    },
  },
  skip: 'Skip to content',
  nav: {
    label: 'Main',
    features: 'Features',
    channels: 'Channels',
    resources: 'Resources',
    pricing: 'Pricing',
    signIn: 'Sign in',
    startTrial: 'Start free trial',
    home: 'Tadween home',
    switchTo: { label: 'ع', title: 'العربية', lang: 'ar' },
    theme: 'Switch between light and dark',
    menu: 'Menu',
    close: 'Close menu',
    breadcrumb: 'Breadcrumb',
    allFeatures: 'See every feature',
    allChannels: 'See all channels',
    spotlight: { title: 'New: the Board', body: 'Every post by status, channel or day, in columns.' },
    resourceLinks: [
      { href: '/#faq', label: 'Questions', body: 'Short answers about Tadween', icon: 'circle-help' },
      { href: '/pricing#compare', label: 'Compare plans', body: 'Every plan, side by side', icon: 'layers' },
      { href: '/ai-agent#connect', label: 'Connect your AI tools', body: 'Claude, ChatGPT and Cursor through MCP', icon: 'plug' },
      { href: '/features/composer#arabic', label: 'Writing in Arabic', body: 'Right to left, in the editor and previews', icon: 'languages' },
      { href: SOURCE_URL, label: 'Open source', body: 'Built on Postiz, AGPL-3.0', icon: 'arrow-up-right', external: true },
    ],
  },
  showcase: {
    like: 'Like',
    comment: 'Comment',
    repost: 'Repost',
    send: 'Send',
    share: 'Share',
    followers: '12,480 followers',
    now: 'Now',
    yesterday: 'Yesterday',
    location: 'Zamalek, Cairo',
    sound: 'original sound',
    commentsShares: '{c} comments · {s} shares',
    status: {
      rakeeza: 'Published · 2h ago',
      qolla: 'Scheduled · Thu 18:00',
      sett: 'Published · Yesterday',
      maadi: 'Scheduled · Tue 09:30',
      felucca: 'Published · 5h ago',
      bunn: 'Scheduled · Fri 08:00',
    },
  },
  shots: {
    today: 'Tadween’s Today page: the next post with a countdown, this week’s posts per day, drafts and channels that need attention',
    'calendar-week': 'The Tadween calendar in week view with posts for LinkedIn, X, Instagram, Facebook and Threads, and past hours shaded',
    'calendar-month': 'The Tadween calendar in month view, with posts on most days',
    'calendar-preview': 'The hover preview of a scheduled LinkedIn post, with its channel, time, full text and actions',
    'preview-failed': 'The hover preview of a failed post on X, with the reason the network gave',
    'calendar-phone': 'The Tadween calendar on a phone, in day view',
    board: 'The Tadween board with columns for drafts, scheduled, published and failed posts',
    'board-channel': 'The Tadween board grouped by channel, one column per account',
    composer: 'The Tadween composer with a post for LinkedIn, X and Threads and the LinkedIn preview beside it',
    'composer-arabic': 'The Tadween composer with an Arabic post written right to left and its preview',
    'composer-phone': 'The Tadween composer on a phone',
    'post-page': 'A post’s shareable page showing how it will look on the network, with comments',
    media: 'The Tadween media library with folders and a grid of images',
    'media-details': 'The details of an image in the media library: alt text, size and the posts that use it',
    'media-upload': 'The upload dock in the media library, showing the progress of each file',
    notifications: 'Tadween notifications: posts published and failed, with what to do next',
    analytics: 'Tadween analytics: posts published from Tadween per day and per network',
    'analytics-channel': 'Tadween analytics for a LinkedIn page: followers, impressions and engagement over time',
    agent: 'The Tadween AI agent: a chat that scheduled three posts, with a card listing them',
    signatures: 'Signatures in Tadween settings, one added to new posts automatically',
    sets: 'Sets in Tadween settings: saved groups of channels with a starting text',
    autopost: 'Auto post settings in Tadween with an RSS feed connected to a LinkedIn profile',
    plugs: 'Plugs in Tadween: automatic reposts and replies when a post passes a number of likes',
    webhooks: 'Webhook settings in Tadween',
    team: 'The team page in Tadween settings, with roles',
  },
  shotUrl: 'tadween',
  hero: {
    eyebrow: 'Built for LinkedIn, fluent in Arabic',
    title: 'Your LinkedIn week, written and scheduled.',
    sub: 'Plan posts for your profile and company pages, see them the way LinkedIn will, and publish at the hour you choose. Then reach 30+ other channels from the same calendar.',
    primary: 'Start 7-day trial',
    secondary: 'See the product',
    fine: 'Seven days free · Cancel any time · Prices in EGP or USD',
    nets: 'LinkedIn, X, Instagram, Facebook, Threads, TikTok and 25 more',
  },
  product: {
    title: 'The calendar your week deserves',
    sub: 'Every channel side by side. Drag a post to move it, rest on it to read it. This is the real app, with a demo workspace.',
    calloutA: 'Rest on a post to read it',
    calloutB: 'Drag to reschedule',
  },
  netstrip: { title: 'Publish to LinkedIn first, and to every network you use', all: 'All channels' },
  tour: {
    title: 'Everything a LinkedIn week needs',
    sub: 'The tools of an open-source scheduler, rebuilt around one network and two languages.',
    rows: [
      {
        href: '/features/composer',
        kicker: 'Composer',
        icon: 'pencil',
        title: 'Write once, see it the way each network will',
        body: 'One editor for every channel, a version per network when you need it, and previews drawn like the feed.',
        points: ['LinkedIn, Instagram, Facebook, TikTok, YouTube and Pinterest previews', 'Length checked per channel', 'First comments with a delay'],
        shot: 'composer',
        link: 'Explore the composer',
      },
      {
        href: '/features/board',
        kicker: 'Board',
        icon: 'square-kanban',
        title: 'Every post by status, in columns',
        body: 'Drafts, scheduled, published and failed side by side, or grouped by channel or day.',
        points: ['Search and filter by client or tag', 'Send a failed post back with a drag'],
        shot: 'board',
        link: 'Explore the board',
      },
      {
        href: '/features/media-library',
        kicker: 'Media library',
        icon: 'folder-open',
        title: 'Find the right image in seconds',
        body: 'Folders inside folders, uploads that keep going while you work, alt text and where each file is used.',
        points: ['Images up to 30 MB, MP4 up to 1 GB', 'Shared by the whole workspace'],
        shot: 'media',
        link: 'Explore the media library',
      },
      {
        href: '/features/analytics',
        kicker: 'Analytics',
        icon: 'chart-column',
        title: 'Numbers you can read in a minute',
        body: 'What you published from Tadween over a year, next to the figures each network shares.',
        points: ['Compare with the previous period', 'Export to CSV'],
        shot: 'analytics',
        link: 'Explore analytics',
      },
    ],
  },
  arabic: {
    title: 'Arabic, done properly',
    sub: 'Write in Arabic and the editor and the previews turn right to left on their own. The whole interface speaks Arabic too, in Tajawal, the same face as this page.',
    bullets: ['Right-to-left editing and previews on every network', 'A full Arabic interface, and English when you switch', 'An English post and an Arabic post for the same moment'],
  },
  agentTeaser: {
    eyebrow: 'AI agent',
    title: 'Ask, and it’s on the calendar.',
    sub: 'Tadween’s agent writes and schedules for you in English or Arabic, inside the app or from Claude, ChatGPT and Cursor.',
    link: 'Meet the agent',
  },
  allFeatures: {
    title: 'And everything around it',
    sub: 'Each tool has its own page, with screenshots of the real app.',
    more: 'See every feature',
  },
  steps: {
    title: 'From idea to published in three steps',
    items: [
      { title: 'Connect', body: 'Link your LinkedIn profile and every page you manage, then any other network. Most networks connect through their own sign-in.' },
      { title: 'Write', body: 'Draft in English or Arabic, add images or a carousel, and check each preview.' },
      { title: 'Schedule', body: 'Pick a time or the next free slot. Tadween publishes and posts your first comment.' },
    ],
  },
  homeFaq: {
    title: 'Questions',
    items: [
      { title: 'What is Tadween?', content: 'A social media scheduler built for LinkedIn first and for Arabic writers. You write, preview and schedule posts for your profile and company pages, and for 30+ other networks, from one calendar.' },
      { title: 'Which networks can I post to?', content: 'LinkedIn profiles and pages, X, Instagram, Facebook, Threads, TikTok, YouTube, Pinterest, Bluesky, Mastodon, Reddit, Telegram, Discord, Slack, Google Business Profile, Medium, Dev.to, Hashnode, WordPress and more.' },
      { title: 'Does it really handle Arabic?', content: 'Yes. The editor and previews turn right to left for Arabic text, the interface is in Arabic, and posts keep their punctuation and numbers where Arabic readers expect them.' },
      { title: 'Can an AI agent schedule for me?', content: 'Yes. Use the agent inside Tadween, or connect Claude, ChatGPT, Cursor or any MCP client. It can write, schedule, list posts and add media. It can’t delete posts.' },
      { title: 'Can my team and clients work in it?', content: 'Invite teammates, keep each client’s channels under their own customer, and send preview links so people can comment before a post goes out.' },
      { title: 'Is there a free trial?', content: 'Every plan starts with seven days free, with prices in Egyptian pounds or US dollars.' },
    ],
  },
  featuresIndex: {
    title: 'Everything in Tadween',
    sub: 'A calm scheduler for LinkedIn and every other channel, in English and Arabic, for one person or a whole agency. Each tool has its own page.',
    agentNav: { label: 'AI agent', blurb: 'Write and schedule by chat, or from Claude and ChatGPT' },
  },
  featurePage: {
    start: 'Start 7-day trial',
    tour: 'See it in action',
    howTitle: 'How it works',
    relatedTitle: 'Works well with',
    faqTitle: 'Questions',
  },
  features: featuresEn,
  agentPage: {
    eyebrow: 'AI agent',
    title: 'Your social media, run by chat',
    sub: 'Ask Tadween’s agent to write, plan and schedule your posts in English or Arabic. Or connect the AI tools you already use, like Claude, ChatGPT and Cursor, to your calendar.',
    chat: { title: 'Tadween agent', online: 'Your channels and calendar', input: 'Ask the agent…' },
    hero: {
      lang: 'en',
      prompt: 'Write three LinkedIn posts about our open studio night, one in Arabic, and schedule them Sunday to Tuesday at 9:00.',
      tools: [
        { tool: 'integrationList', label: 'Found Nile Studio on LinkedIn and 2 pages' },
        { tool: 'integrationSchema', label: 'Checked LinkedIn’s rules and limits' },
        { tool: 'integrationSchedulePostTool', label: 'Scheduled 3 posts' },
      ],
      reply: 'Done. Three posts are on your calendar; the Monday one is in Arabic. Open any of them to edit before it goes out.',
      posts: [
        { net: 'linkedin', name: 'Nile Studio', text: 'Nile Studio is hosting its first open studio night…', when: 'Sun 09:00' },
        { net: 'linkedin', name: 'Nile Studio', text: 'ستوديو النيل بيفتح أبوابه يوم ٢٢ أكتوبر…', when: 'Mon 09:00' },
        { net: 'linkedin', name: 'Nile Studio', text: 'Three things we will talk about on the 22nd…', when: 'Tue 09:00' },
      ],
    },
    works: {
      title: 'Works with the AI tools you already use',
      sub: 'Anything that speaks MCP can read your calendar and schedule posts with your permission.',
      items: ['Claude', 'ChatGPT', 'Claude Code', 'Cursor', 'VS Code', 'Windsurf', 'Codex', 'Gemini CLI'],
      note: 'Names are trademarks of their owners. Tadween isn’t affiliated with them.',
    },
    connect: {
      title: 'Connect your AI tool in a minute',
      sub: 'Copy one address into the AI tool you already use and sign in to Tadween when it asks. For Claude, ChatGPT and Cursor there is no key to paste.',
      connectTitle: 'Copy the Tadween MCP address',
      connectBody: 'One address for Claude, ChatGPT and Cursor. Your tool opens Tadween so you can sign in and approve it.',
      linkLabel: 'Tadween MCP address',
      copy: 'Copy',
      copied: 'Copied',
      askTitle: 'Ask your agent to post',
      askBody: 'Ask it to list your channels to check the connection, then to write and schedule in plain words.',
      ask: {
        lang: 'en',
        prompt: 'Schedule a post to our LinkedIn page for tomorrow at 9:00 about the cupping session.',
        tools: [{ tool: 'integrationSchedulePostTool', label: 'Scheduled 1 post' }],
        reply: 'Done. It goes out on Cairo Coffee Co. tomorrow at 09:00. Want me to add the photo from your library?',
        posts: [{ net: 'linkedin-page', name: 'Cairo Coffee Co.', text: 'Cupping session this Thursday at 18:00…', when: 'Sat 09:00' }],
      },
      alsoTry: 'Also try',
      suggestions: ['List my connected channels', 'What goes out this week?', 'Plan next week in Arabic and English'],
      steps: [
        { title: 'Copy the address', body: 'The same address for every client and every workspace.' },
        { title: 'Add it to your tool', body: 'As a custom connector, or a remote MCP server over HTTP.' },
        { title: 'Sign in to Tadween', body: 'Your tool opens Tadween; approve it for your workspace.' },
        { title: 'Ask', body: '“What’s scheduled on LinkedIn this week?” is a good first question.' },
      ],
      clientsTitle: 'Step by step, for your tool',
      clientsSub: 'The same tools in each. Settings, API & MCP in Tadween shows these for your workspace too.',
      clients: [
        {
          name: 'Claude and ChatGPT',
          how: 'A custom connector, signed in with OAuth',
          steps: ['Open your connectors and add a custom one', 'Paste the Tadween MCP address', 'Sign in to Tadween and approve it'],
          codeLabel: 'Connector address',
          code: '{api}/mcp-oauth-dynamic',
        },
        {
          name: 'Claude Code',
          how: 'One command in your terminal',
          steps: ['Run the command below', 'Sign in to Tadween in the browser tab that opens'],
          codeLabel: 'Terminal',
          code: 'claude mcp add --transport http tadween "{api}/mcp-oauth-dynamic"',
        },
        {
          name: 'Cursor',
          how: 'A remote MCP server in the client’s settings',
          steps: ['Add the server to your MCP settings', 'Sign in to Tadween when the client asks'],
          codeLabel: '.cursor/mcp.json',
          code: '{\n  "mcpServers": {\n    "tadween": {\n      "url": "{api}/mcp-oauth-dynamic"\n    }\n  }\n}',
        },
      ],
      keyNote: 'Another MCP client, or prefer a key? Use {api}/mcp with your key from Settings, API & MCP in an “Authorization: Bearer” header. Never put the key in a URL.',
    },
    examples: {
      title: 'Things people ask',
      sub: 'Each ends the same way: posts on your calendar, ready for you to check.',
      items: [
        {
          lang: 'en',
          prompt: 'Turn this blog post into a LinkedIn post and an X post, and schedule both for tomorrow at 8:45.',
          tools: [{ tool: 'integrationSchedulePostTool', label: 'Scheduled 2 posts' }],
          reply: 'Both are scheduled for tomorrow at 08:45, shortened to fit X.',
          posts: [
            { net: 'linkedin', name: 'Nile Studio', text: 'What 200 bilingual posts taught us…', when: 'Sat 08:45' },
            { net: 'x', name: 'Rakeeza', text: '200 bilingual posts, 3 lessons ↓', when: 'Sat 08:45' },
          ],
        },
        {
          lang: 'ar',
          prompt: 'اكتب منشور لصفحة Cairo Coffee Co. عن جلسة التذوق يوم الخميس، وجدوله بكرة الساعة ٨ الصبح.',
          tools: [{ tool: 'integrationSchedulePostTool', label: 'جدول منشورًا واحدًا' }],
          reply: 'تمام، المنشور مجدول بكرة الساعة ٨:٠٠ على صفحة Cairo Coffee Co.',
          posts: [{ net: 'linkedin-page', name: 'Cairo Coffee Co.', text: 'جلسة تذوق يوم الخميس الساعة ٦…', when: 'السبت ٠٨:٠٠' }],
        },
        {
          lang: 'en',
          prompt: 'What’s scheduled for Maadi Lane Homes next week? Save a draft for Friday about the show flat.',
          tools: [
            { tool: 'postsListTool', label: 'Found 2 posts next week' },
            { tool: 'integrationSchedulePostTool', label: 'Saved 1 draft' },
          ],
          reply: 'Two posts are scheduled, Monday and Thursday. The Friday draft is waiting in your drafts.',
          posts: [{ net: 'linkedin-page', name: 'Maadi Lane Homes', text: 'Show flat open this Friday and Saturday…', when: 'Draft · Fri' }],
        },
      ],
    },
    can: {
      title: 'What the agent can do',
      sub: 'The same tools power the agent in Tadween and your AI client.',
      items: [
        { icon: 'pencil', title: 'Write posts', body: 'Drafts in English or Arabic, shaped for each network and its character limit.' },
        { icon: 'calendar', title: 'Schedule or publish', body: 'Picks the channels, checks each network’s settings, and schedules, saves a draft or publishes now.' },
        { icon: 'calendar-days', title: 'Read your calendar', body: 'Lists the posts in any period, so you can ask what goes out this week.' },
        { icon: 'upload', title: 'Bring in media', body: 'Imports an image or video from a public link into your media library and attaches it.' },
        { icon: 'image', title: 'Make images and video', body: 'Generates images or short videos for a post, with your plan’s AI credits.' },
        { icon: 'users', title: 'Work per client', body: 'Lists your customers and their channels, so agencies keep clients apart.' },
      ],
    },
    cannot: 'The agent can’t delete posts or rewrite one that is already scheduled. Those stay your decisions, in the calendar.',
    inApp: {
      title: 'Inside Tadween, with nothing to set up',
      sub: 'Open the agent from the sidebar. It knows your channels, your customers and your calendar, and keeps your past chats.',
      points: ['Pick channels and a customer for the chat', 'Suggested prompts to start from', 'Cards that show exactly what it scheduled'],
    },
    connectors: {
      title: 'Connectors, coming soon',
      sub: 'We are adding connectors so the agent can pull from the tools you already use and publish from them.',
      badge: 'Coming soon',
      items: [
        { icon: 'hard-drive', title: 'Google Drive and Dropbox', body: 'Pick images and video straight from your drives.' },
        { icon: 'file-text', title: 'Notion and Google Docs', body: 'Turn a doc or a page into posts for each channel.' },
        { icon: 'rss', title: 'Blogs and RSS', body: 'Smarter auto-posting from your blog, with drafts to review.' },
        { icon: 'layers', title: 'Canva', body: 'Bring designs into the media library without downloading them.' },
        { icon: 'users', title: 'HubSpot', body: 'Plan campaigns around your CRM and report back.' },
        { icon: 'bell', title: 'Slack and Microsoft Teams', body: 'Get told when a post publishes or fails.' },
      ],
      planNote: 'Planned, not built yet. The order may change.',
    },
    faqTitle: 'Questions',
    faq: [
      { title: 'Which AI tools can I connect?', content: 'Any client that supports MCP over HTTP: Claude, ChatGPT, Claude Code, Cursor, VS Code, Windsurf, Codex, Gemini CLI and more. Claude and ChatGPT can also sign in with OAuth instead of an API key.' },
      { title: 'Where do I find my API key?', content: 'In Tadween, open Settings, then API & MCP. You can copy the key and see the settings for each client there.' },
      { title: 'Will the agent post without asking me?', content: 'It does what you ask, and it asks before it schedules anything. You can always open the post on the calendar, edit it or delete it.' },
      { title: 'Can it delete posts?', content: 'No. The agent has no delete tool, and it can’t rewrite a post that is already scheduled. Those stay in the calendar.' },
      { title: 'Does it write in Arabic?', content: 'Yes. Ask in Arabic or English and say which language the post should be in.' },
      { title: 'Is the agent on every plan?', content: 'The agent and the MCP connection come with every paid plan. Generated images and videos use your plan’s AI credits.' },
    ],
  },
  pricing: {
    sectionTitle: 'Simple pricing, in pounds or dollars',
    sectionSub: 'Every plan starts with seven days free.',
    pageTitle: 'Pricing',
    pageSub: 'Four plans for people, brands and agencies on LinkedIn. Every plan starts with seven days free.',
    periodLabel: 'Billing period',
    monthly: 'Monthly',
    yearly: 'Yearly',
    currencyLabel: 'Currency',
    currencies: { EGP: 'EGP', USD: 'USD' },
    save: 'Save 20% yearly',
    placeholder: 'Placeholder prices',
    mostPopular: 'Most popular',
    perMonth: '/ month',
    billedMonthly: 'Billed monthly',
    billedYearly: 'Billed {amount} yearly',
    perMonthShort: '/mo',
    trial: 'Start 7-day trial',
    note: 'These prices are placeholders while plans are finalised. Final prices show here before launch.',
    noteApi: 'Prices come from the plans set in Tadween. EGP amounts are placeholders until local payments launch.',
    compareTitle: 'Compare plans',
    compareLink: 'Compare every plan',
    included: 'Included',
    notIncluded: 'Not included',
    notListed: 'Not listed',
    faqTitle: 'Questions',
    unlimited: 'Unlimited',
    plans: [
      { key: 'creator', name: 'Creator', for: 'For one voice on LinkedIn', features: ['Profile + 1 company page', 'Unlimited scheduled posts', 'Calendar, board and network previews', 'First comments and repeats', 'Analytics'] },
      { key: 'pro', name: 'Pro', for: 'For creators who post every week', features: ['5 channels', 'Everything in Creator', 'AI writing assistant', 'Image carousels on LinkedIn', 'Sets and signatures'] },
      { key: 'team', name: 'Team', for: 'For brands with a team', features: ['15 channels', 'Everything in Pro', 'Unlimited team members', 'Preview links for clients', 'Shared calendar and tags'] },
      { key: 'agency', name: 'Agency', for: 'For agencies and many clients', features: ['50 channels', 'Everything in Team', 'Each client under their own customer', 'Room for many brands'] },
    ],
    compare: [
      { label: 'Channels', help: 'LinkedIn profiles and pages, and any other network you connect.', field: 'channels' },
      { label: 'Scheduled posts', help: 'Posts you can schedule each month.', values: { creator: '∞', pro: '∞', team: '∞', agency: '∞' } },
      { label: 'Team members', help: 'People who can write and schedule with you.', field: 'teamMembers' },
      { label: 'AI credits a month', help: 'Credits for AI-generated images and videos.', field: 'aiCredits' },
      { label: 'Preview links', help: 'Send anyone a link to see a post and leave comments.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'First comments and delays', help: 'Post a comment minutes after the post.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Repeated posts', help: 'Republish evergreen posts on a schedule.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Analytics', help: 'Channel and post results, where the network shares them.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Sets and signatures', help: 'Saved channel groups and sign-offs.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'RSS auto-post', help: 'Turn new items from a feed into posts.', field: 'autoPost' },
      { label: 'Webhooks', help: 'HTTP callbacks when a post is published.', field: 'webhooks' },
      { label: 'Public API and MCP', help: 'Schedule from Claude, ChatGPT, Cursor or your own code.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Customer groups', help: 'Keep each client’s channels apart.', values: { creator: true, pro: true, team: true, agency: true } },
    ],
    faq: [
      { title: 'Is there a free trial?', content: 'Every plan starts with a 7-day free trial. You only pay if you keep using Tadween.' },
      { title: 'Can I pay in Egyptian pounds?', content: 'Prices show in Egyptian pounds and US dollars. The payment methods for your region are shown at checkout.' },
      { title: 'Does it work with LinkedIn company pages?', content: 'Yes. Connect your profile and every page you admin, then schedule to one or many at once.' },
      { title: 'Can I write in Arabic?', content: 'Tadween is built right-to-left from the start: Arabic previews, right-to-left writing and an Arabic interface.' },
      { title: 'Is the API and MCP server on every plan?', content: 'Yes. Every paid plan includes the public API and the MCP server, so you can schedule from Claude, ChatGPT or your own code.' },
    ],
  },
  cta: {
    title: 'Plan next week in ten minutes.',
    body: 'Seven days free. Bring your LinkedIn profile and pages.',
    primary: 'Start 7-day trial',
    secondary: 'Sign in',
  },
  channels: channelsEn,
  footer: {
    tagline: 'LinkedIn scheduling for people and brands in Egypt and the region.',
    channelsTitle: 'Channels',
    toolsTitle: 'Features',
    columns: [
      {
        title: 'Product',
        links: [
          { href: '/features', label: 'All features' },
          { href: '/ai-agent', label: 'AI agent' },
          { href: '/channels', label: 'Channels' },
          { href: '/pricing', label: 'Pricing' },
          { href: SIGN_UP_URL, label: 'Start free trial' },
          { href: SIGN_IN_URL, label: 'Sign in' },
        ],
      },
      {
        title: 'Open source',
        links: [
          { href: SOURCE_URL, label: 'Source code', external: true },
          { href: LICENSE_URL, label: 'AGPL-3.0 license', external: true },
        ],
      },
    ],
    copyright: '© 2026 Tadween.',
  },
};
