import { LICENSE_URL, SIGN_IN_URL, SIGN_UP_URL, SOURCE_URL } from '@/lib/config';
import type { Dict } from './types';

// English copy, from the design system's landing and pricing components
// (components/src/pages.tsx). Sentence case, no emoji, no invented stats.
export const en: Dict = {
  lang: 'en',
  dir: 'ltr',
  base: '',
  numberLocale: 'en-US',
  meta: {
    title: 'Tadween — LinkedIn scheduling, written in two languages',
    description:
      'Plan LinkedIn posts for your profile and company pages, preview them exactly as LinkedIn will show them, and publish at the hour your audience is reading. In English and Arabic.',
    pricingTitle: 'Pricing — Tadween',
    pricingDescription:
      'Four plans for people, brands and agencies on LinkedIn. Every plan starts with seven days free. Pay in Egyptian pounds or US dollars.',
    ogLocale: 'en_US',
  },
  skip: 'Skip to content',
  nav: {
    label: 'Main',
    links: [
      { href: '/#features', label: 'Product' },
      { href: '/#flow', label: 'How it works' },
      { href: '/#arabic', label: 'Arabic' },
      { href: '/pricing', label: 'Pricing' },
    ],
    signIn: 'Sign in',
    startTrial: 'Start free trial',
    home: 'Tadween home',
    switchTo: { label: 'ع', title: 'العربية', lang: 'ar' },
    theme: 'Switch between light and dark',
  },
  hero: {
    eyebrow: 'Built for LinkedIn, fluent in Arabic',
    title: 'Your LinkedIn week, written and scheduled.',
    sub: 'Plan posts for your profile and company pages, see them exactly as LinkedIn will, and publish at the hour your audience is reading.',
    primary: 'Start 7-day trial',
    secondary: 'See how it works',
    fine: 'No card needed · Cancel any time · Pay in EGP or USD',
    tagBest: 'Best time · Wed 08:45',
    tagScheduled: '8 posts scheduled',
    scroll: 'Scroll',
  },
  linkedin: {
    you: 'You',
    now: 'Now',
    visibleToAnyone: 'Visible to anyone',
    comments: 'comments',
    reposts: 'reposts',
    actions: ['Like', 'Comment', 'Repost', 'Send'],
  },
  flow: {
    title: 'From idea to published, in one calm flow.',
    steps: [
      { title: 'Write', body: 'Draft in English or Arabic. The smart layer suggests a stronger first line.', icon: 'pencil' },
      { title: 'Preview', body: 'See the post exactly as the feed will: “…more”, images, first comment.', icon: 'eye' },
      { title: 'Schedule', body: 'Drop it on the calendar, or take the best time for your audience.', icon: 'calendar' },
    ],
    author: { name: 'Mona Adel', headline: 'Founder at Studio Nile', initials: 'MA' },
    text: 'We hired our first 10 engineers in Cairo in 90 days.\n\nThree things made it work — and none of them was a recruiter.',
    chipWhen: 'Wed 14 Oct · 08:45',
    chipWhere: 'Scheduled on 2 channels',
  },
  features: {
    title: 'Everything a LinkedIn week needs',
    sub: 'The full power of an open-source scheduler, rebuilt around one network and two languages.',
    items: [
      { icon: 'calendar-days', title: 'A calendar that feels physical', body: 'Drag posts between days; they follow your hand and settle into place. Day, week, month and list views.' },
      { icon: 'eye', title: 'See it before LinkedIn does', body: 'Pixel-true previews for profiles and pages, on desktop and mobile, with “…more”, carousels and first comments.' },
      { icon: 'sparkles', title: 'A quiet smart layer', body: 'Best-time hints and stronger hooks, drawn from your own posts. Nothing changes until you apply it.', smart: true },
      { icon: 'languages', title: 'Arabic, done properly', body: 'Right-to-left editor and previews, Arabic digits, and rewrites written for Egyptian and Gulf readers.' },
      { icon: 'message-square', title: 'First comments, on time', body: 'Put links in the first comment and post it minutes later, so your reach stays high.' },
      { icon: 'users', title: 'Approvals for teams', body: 'Drafts go to a reviewer, clients stay in their own groups, and everyone sees one calendar.' },
    ],
  },
  steps: {
    title: 'From idea to published in three steps',
    items: [
      { icon: 'link', title: 'Connect', body: 'Link your LinkedIn profile and every page you manage. Two clicks, no passwords stored.' },
      { icon: 'pencil', title: 'Write', body: 'Draft in English or Arabic, add images or a PDF carousel, and check the preview.' },
      { icon: 'calendar', title: 'Schedule', body: 'Pick a time, or take the suggested best time. Tadween publishes and posts your first comment.' },
    ],
  },
  arabic: {
    title: 'Write in Arabic. See it right.',
    sub: 'Most schedulers flip Arabic into a mess of reversed punctuation. Tadween previews, edits and publishes right-to-left text exactly as your readers see it.',
    bullets: ['Right-to-left editor and preview', 'Arabic interface and support', 'Hook rewrites in Modern Standard Arabic'],
  },
  pricing: {
    sectionTitle: 'Simple pricing, in pounds or dollars',
    sectionSub: 'Every plan starts with seven days free.',
    pageTitle: 'Pricing',
    pageSub: 'Four plans for people, brands and agencies on LinkedIn. Every plan starts with seven days free.',
    periodLabel: 'Billing period',
    monthly: 'Monthly',
    yearly: 'Yearly',
    currencyLabel: 'Currency',
    currencies: { EGP: 'EGP', USD: 'USD' },
    save: 'Save 20% yearly',
    placeholder: 'Placeholder prices',
    mostPopular: 'Most popular',
    perMonth: '/ month',
    billedMonthly: 'Billed monthly',
    billedYearly: 'Billed {amount} yearly',
    perMonthShort: '/mo',
    trial: 'Start 7-day trial',
    note: 'These prices are placeholders while plans are finalised. Final prices show here before launch.',
    noteApi: 'Prices come from the plans set in Tadween. EGP amounts are placeholders until local payments launch.',
    compareTitle: 'Compare plans',
    compareLink: 'Compare every plan',
    included: 'Included',
    notIncluded: 'Not included',
    notListed: 'Not listed',
    faqTitle: 'Questions',
    plans: [
      { key: 'creator', name: 'Creator', for: 'For one voice on LinkedIn', features: ['Profile + 1 company page', 'Unlimited scheduled posts', 'First comments and repeats', 'Best-time hints', 'Analytics'] },
      { key: 'pro', name: 'Pro', for: 'For creators who post every week', features: ['5 LinkedIn channels', 'Everything in Creator', 'Hook rewrites in Arabic and English', 'PDF carousel builder', 'Sets and signatures'] },
      { key: 'team', name: 'Team', for: 'For brands with a team', features: ['15 channels', 'Unlimited team members', 'Approval workflow', 'Shared calendar and tags', 'Agent and MCP access'] },
      { key: 'agency', name: 'Agency', for: 'For agencies and many clients', features: ['50 channels', 'Customer groups', 'Client-ready reports', 'Priority support in Arabic', 'Invoices in EGP or USD'] },
    ],
    compare: [
      { label: 'LinkedIn channels', help: 'Profiles and company pages you can connect.', values: { creator: '2', pro: '5', team: '15', agency: '50' } },
      { label: 'Scheduled posts', help: 'Posts you can schedule each month.', values: { creator: '∞', pro: '∞', team: '∞', agency: '∞' } },
      { label: 'Team members', help: 'People who can draft, review and schedule.', values: { creator: false, pro: false, team: true, agency: true } },
      { label: 'Approval workflow', help: 'Send posts for review before they go live.', values: { creator: false, pro: false, team: true, agency: true } },
      { label: 'First comments and delays', help: 'Post a comment minutes after the post.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Repeated posts', help: 'Republish evergreen posts on a schedule.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Best-time hints', help: 'When your audience opens LinkedIn.', values: { creator: true, pro: true, team: true, agency: true } },
      { label: 'Hook rewrites', help: 'Stronger first lines in Arabic or English.', values: { creator: false, pro: true, team: true, agency: true } },
      { label: 'PDF carousels', help: 'Turn images into a swipeable document post.', values: { creator: false, pro: true, team: true, agency: true } },
      { label: 'Sets and signatures', help: 'Saved channel groups and sign-offs.', values: { creator: false, pro: true, team: true, agency: true } },
      { label: 'Agent, MCP and API', help: 'Schedule from Claude, ChatGPT or your tools.', values: { creator: false, pro: false, team: true, agency: true } },
      { label: 'Customer groups', help: 'Keep each client’s channels apart.', values: { creator: false, pro: false, team: false, agency: true } },
      { label: 'Webhooks and RSS auto-post', help: 'Integrate and automate.', values: { creator: true, pro: true, team: true, agency: true } },
    ],
    faq: [
      { title: 'Is there a free trial?', content: 'Every plan starts with a 7-day free trial. You only pay if you keep using Tadween.' },
      { title: 'Can I pay in Egyptian pounds?', content: 'Yes. Pay in EGP with a local card or wallet, or in USD with any international card. Invoices are issued in the currency you pay with.' },
      { title: 'Does it work with LinkedIn company pages?', content: 'Yes. Connect your profile and every page you admin, then schedule to one or many at once.' },
      { title: 'Can I write in Arabic?', content: 'Tadween is built right-to-left from the start: Arabic previews, Arabic hook rewrites, and an Arabic interface.' },
      { title: 'Can I change or cancel my plan?', content: 'Any time from Billing. Upgrades apply immediately with a prorated charge; downgrades apply at the end of the period.' },
      { title: 'What happens to scheduled posts if I cancel?', content: 'They stay in your calendar as drafts until the end of your billing period, then pause. Nothing is deleted.' },
    ],
  },
  cta: {
    title: 'Plan next week in ten minutes.',
    body: 'Seven days free. Bring your LinkedIn profile and pages.',
    primary: 'Start 7-day trial',
    secondary: 'Sign in',
  },
  footer: {
    tagline: 'LinkedIn scheduling for people and brands in Egypt and the region.',
    columns: [
      {
        title: 'Product',
        links: [
          { href: '/#features', label: 'Calendar' },
          { href: '/#flow', label: 'Previews' },
          { href: '/#features', label: 'Smart layer' },
          { href: '/#arabic', label: 'Arabic' },
          { href: '/pricing', label: 'Pricing' },
        ],
      },
      {
        title: 'Account',
        links: [
          { href: SIGN_UP_URL, label: 'Start free trial' },
          { href: SIGN_IN_URL, label: 'Sign in' },
        ],
      },
      {
        title: 'Open source',
        links: [
          { href: SOURCE_URL, label: 'Source code', external: true },
          { href: LICENSE_URL, label: 'AGPL-3.0 license', external: true },
        ],
      },
    ],
    copyright: '© 2026 Tadween.',
  },
};
